import { snapToCell } from "./geoprivacy";
import type { Availability, LookingFor, RadarProfile } from "./radar-types";
import { RADAR_CITY_ID } from "./radar-types";
import type { Visibility } from "./geoprivacy";

/**
 * Stand-in for the `profiles` rows the radar reads. Positions here are already
 * snapped through `snapToCell` at construction — the true coordinate never
 * survives past this module, exactly as the client-side snap works in the app.
 */
type Seed = {
  id: string;
  display_name: string;
  headline: string;
  skills: string[];
  looking_for: LookingFor[];
  availability: Availability;
  bio: string;
  links: { label: string; url: string }[];
  visibility: Visibility;
  /** Approximate area only; snapped immediately below. */
  lat: number;
  lng: number;
  hours_ago: number;
};

const SEEDS: Seed[] = [
  {
    id: "p-mara",
    display_name: "Mara Ilves",
    headline: "Fractional CTO for seed-stage fintech",
    skills: ["TypeScript", "Payments", "Team scaling", "AWS"],
    looking_for: ["contract_work", "collaborators"],
    availability: "limited",
    bio: "Ten years building payment rails, last four as a contractor. Currently rebuilding a ledger for a Singapore lender two days a week; the rest is open. I like scoped, unglamorous, load-bearing work.",
    links: [{ label: "Site", url: "https://example.com/mara" }],
    visibility: "radar",
    lat: -8.6553,
    lng: 115.1306,
    hours_ago: 0,
  },
  {
    id: "p-dev",
    display_name: "Dev Anand",
    headline: "Building a compliance API for remote payroll",
    skills: ["Go", "Postgres", "Product"],
    looking_for: ["cofounder", "hiring"],
    availability: "available",
    bio: "Solo founder, twelve paying customers, looking for a technical cofounder who has felt the pain of cross-border contractor payments personally.",
    links: [{ label: "Product", url: "https://example.com/payroll" }],
    visibility: "radar",
    lat: -8.6558,
    lng: 115.1301,
    hours_ago: 2,
  },
  {
    id: "p-noor",
    display_name: "Noor Haddad",
    headline: "Brand and product design, B2B SaaS only",
    skills: ["Figma", "Design systems", "Landing pages"],
    looking_for: ["contract_work"],
    availability: "available",
    bio: "I do the unfashionable part of design: making dense product surfaces legible. Six-week engagements, fixed scope, no retainers.",
    links: [{ label: "Portfolio", url: "https://example.com/noor" }],
    visibility: "radar",
    lat: -8.6547,
    lng: 115.1309,
    hours_ago: 5,
  },
  {
    id: "p-tomas",
    display_name: "Tomás Ferreira",
    headline: "Data engineer, warehouse migrations",
    skills: ["dbt", "Snowflake", "Python", "Airflow"],
    looking_for: ["contract_work", "coffee"],
    availability: "booked",
    bio: "Booked through November but always up for a coffee about pipeline architecture. Portuguese tax resident, so ask me about the D8 paperwork.",
    links: [],
    visibility: "radar",
    lat: -8.6551,
    lng: 115.1298,
    hours_ago: 9,
  },
  {
    id: "p-ines",
    display_name: "Inés Rueda",
    headline: "Growth for developer tools",
    skills: ["SEO", "Content", "Analytics"],
    looking_for: ["collaborators", "contract_work"],
    availability: "limited",
    bio: "Ex-DevRel, now running growth experiments for three API companies. Happy to swap notes on technical content that actually converts.",
    links: [{ label: "Writing", url: "https://example.com/ines" }],
    visibility: "radar",
    lat: -8.6556,
    lng: 115.1311,
    hours_ago: 20,
  },
  {
    id: "p-kenji",
    display_name: "Kenji Morita",
    headline: "iOS engineer, offline-first apps",
    skills: ["Swift", "SQLite", "Mobile perf"],
    looking_for: ["contract_work"],
    availability: "available",
    bio: "Fifteen shipped apps. Specialised in the ones that have to work with no signal — field ops, logistics, marine.",
    links: [],
    visibility: "radar",
    lat: -8.6549,
    lng: 115.1303,
    hours_ago: 30,
  },
  {
    id: "p-adaeze",
    display_name: "Adaeze Okonkwo",
    headline: "Founder — climate reporting for SMEs",
    skills: ["Product", "Regulatory", "Sales"],
    looking_for: ["cofounder", "hiring"],
    availability: "available",
    bio: "Pre-seed, two pilots signed in the EU. Need someone who can build the data ingestion side and wants equity, not an invoice.",
    links: [{ label: "Deck", url: "https://example.com/climate" }],
    visibility: "radar",
    lat: -8.6474,
    lng: 115.1381,
    hours_ago: 1,
  },
  {
    id: "p-luka",
    display_name: "Luka Petrović",
    headline: "Backend contractor, Rust and Elixir",
    skills: ["Rust", "Elixir", "Distributed systems"],
    looking_for: ["contract_work", "collaborators"],
    availability: "limited",
    bio: "I take over projects that are melting under load. Belgrade base, three months a year here.",
    links: [],
    visibility: "radar",
    lat: -8.6469,
    lng: 115.1388,
    hours_ago: 4,
  },
  {
    id: "p-sara",
    display_name: "Sara Lindqvist",
    headline: "Technical writer and docs architect",
    skills: ["Docs", "API reference", "Information architecture"],
    looking_for: ["contract_work", "coffee"],
    availability: "available",
    bio: "If your docs are a wiki graveyard I will fix that. Prefer three-month engagements with engineering access.",
    links: [{ label: "Samples", url: "https://example.com/sara" }],
    visibility: "radar",
    lat: -8.6477,
    lng: 115.1377,
    hours_ago: 12,
  },
  {
    id: "p-elias",
    display_name: "Elias Kimani",
    headline: "ML engineer — retrieval and evals",
    skills: ["Python", "RAG", "Evals", "PyTorch"],
    looking_for: ["collaborators", "cofounder"],
    availability: "limited",
    bio: "Building eval harnesses for support automation. Interested in a cofounder with distribution, not another modeller.",
    links: [],
    visibility: "radar",
    lat: -8.6471,
    lng: 115.1384,
    hours_ago: 26,
  },
  {
    id: "p-hana",
    display_name: "Hana Suzuki",
    headline: "Fractional finance for solo founders",
    skills: ["Bookkeeping", "Tax structuring", "Runway modelling"],
    looking_for: ["contract_work", "coffee"],
    availability: "available",
    bio: "I keep twenty one-person companies compliant across four jurisdictions. Ask me before you register anything anywhere.",
    links: [],
    visibility: "radar",
    lat: -8.6476,
    lng: 115.1379,
    hours_ago: 48,
  },
  {
    id: "p-marco",
    display_name: "Marco Bianchi",
    headline: "Video and motion for product launches",
    skills: ["After Effects", "Editing", "Scripting"],
    looking_for: ["contract_work"],
    availability: "booked",
    bio: "Launch films and demo videos. Booked to December, taking January bookings now.",
    links: [{ label: "Reel", url: "https://example.com/marco" }],
    visibility: "city",
    lat: -8.6702,
    lng: 115.1442,
    hours_ago: 6,
  },
  {
    id: "p-priya",
    display_name: "Priya Raman",
    headline: "Security engineer, SOC 2 without the theatre",
    skills: ["AppSec", "Compliance", "Threat modelling"],
    looking_for: ["contract_work", "collaborators"],
    availability: "limited",
    bio: "I get small teams audit-ready without turning the whole company into a checklist factory.",
    links: [],
    visibility: "radar",
    lat: -8.6706,
    lng: 115.1447,
    hours_ago: 14,
  },
  {
    id: "p-jonas",
    display_name: "Jonas Weber",
    headline: "Founder — marketplace for surf schools",
    skills: ["Ops", "Marketplaces", "Bali logistics"],
    looking_for: ["hiring", "coffee"],
    availability: "available",
    bio: "Bootstrapped, profitable, boring in the good way. Hiring a part-time growth person who is actually here.",
    links: [],
    visibility: "radar",
    lat: -8.6698,
    lng: 115.1438,
    hours_ago: 33,
  },
  {
    id: "p-yara",
    display_name: "Yara Nassif",
    headline: "Full-stack dev, Next.js and Postgres",
    skills: ["React", "Postgres", "TypeScript"],
    looking_for: ["contract_work", "collaborators"],
    availability: "available",
    bio: "Two-week sprints for early-stage teams. I ship, I document, I hand it over cleanly.",
    links: [],
    visibility: "radar",
    lat: -8.6915,
    lng: 115.1688,
    hours_ago: 7,
  },
  {
    id: "p-oliver",
    display_name: "Oliver Grant",
    headline: "Ops consultant for remote-first teams",
    skills: ["Hiring", "Process", "Notion"],
    looking_for: ["contract_work", "coffee"],
    availability: "limited",
    bio: "I build the boring internal scaffolding that stops a fifteen-person remote team from grinding to a halt.",
    links: [],
    visibility: "radar",
    lat: -8.5071,
    lng: 115.2627,
    hours_ago: 18,
  },
  {
    id: "p-ghosted",
    display_name: "Anon",
    headline: "Ghost mode — should never render",
    skills: [],
    looking_for: ["coffee"],
    availability: "available",
    bio: "",
    links: [],
    visibility: "ghost",
    lat: -8.6553,
    lng: 115.1306,
    hours_ago: 1,
  },
  {
    id: "p-stale",
    display_name: "Stale User",
    headline: "Past the radar TTL — should never render",
    skills: [],
    looking_for: ["coffee"],
    availability: "available",
    bio: "",
    links: [],
    visibility: "radar",
    lat: -8.6553,
    lng: 115.1306,
    hours_ago: 24 * 12,
  },
];

const BASE_NOW = Date.parse("2026-08-04T12:00:00Z");

export const RADAR_PEERS: RadarProfile[] = SEEDS.map((s) => {
  const cell = snapToCell(s.lat, s.lng);
  return {
    id: s.id,
    display_name: s.display_name,
    avatar_url: null,
    headline: s.headline,
    skills: s.skills,
    looking_for: s.looking_for,
    availability: s.availability,
    bio: s.bio,
    links: s.links,
    timezone: "Asia/Makassar",
    visibility: s.visibility,
    cell_lat: cell.lat,
    cell_lng: cell.lng,
    last_active_at: new Date(BASE_NOW - s.hours_ago * 3_600_000).toISOString(),
    radar_city_id: RADAR_CITY_ID,
  };
});

/** People waiting for the radar to open in cities where it is not live yet. */
export const RADAR_WAITLIST_COUNTS: Record<string, number> = {
  "lisbon-pt": 148,
  "chiang-mai-th": 96,
  "mexico-city-mx": 87,
  "medellin-co": 71,
  "bangkok-th": 64,
  "tbilisi-ge": 52,
  "las-palmas-es": 44,
  "cape-town-za": 38,
  "budapest-hu": 29,
  "taipei-tw": 24,
};

export function waitingCount(cityId: string): number {
  return RADAR_WAITLIST_COUNTS[cityId] ?? 12;
}
