/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as CityCityIdRouteImport } from './routes/city.$cityId'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityPeerIdRouteImport } from './routes/community.$peerId'
import { Route as CommunityRequestsRouteImport } from './routes/community.requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCityIdRoute = CityCityIdRouteImport.update({
  id: '/city/$cityId',
  path: '/city/$cityId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPeerIdRoute = CommunityPeerIdRouteImport.update({
  id: '/community/$peerId',
  path: '/community/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRequestsRoute = CommunityRequestsRouteImport.update({
  id: '/community/requests',
  path: '/community/requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/stays': typeof StaysRoute
  '/tracker': typeof TrackerRoute
  '/city/$cityId': typeof CityCityIdRoute
  '/community/$peerId': typeof CommunityPeerIdRoute
  '/community/requests': typeof CommunityRequestsRoute
  '/community/': typeof CommunityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/stays': typeof StaysRoute
  '/tracker': typeof TrackerRoute
  '/city/$cityId': typeof CityCityIdRoute
  '/community/$peerId': typeof CommunityPeerIdRoute
  '/community/requests': typeof CommunityRequestsRoute
  '/community': typeof CommunityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/stays': typeof StaysRoute
  '/tracker': typeof TrackerRoute
  '/city/$cityId': typeof CityCityIdRoute
  '/community/$peerId': typeof CommunityPeerIdRoute
  '/community/requests': typeof CommunityRequestsRoute
  '/community/': typeof CommunityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/compare'
    | '/pricing'
    | '/profile'
    | '/stays'
    | '/tracker'
    | '/city/$cityId'
    | '/community/$peerId'
    | '/community/requests'
    | '/community/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/compare'
    | '/pricing'
    | '/profile'
    | '/stays'
    | '/tracker'
    | '/city/$cityId'
    | '/community/$peerId'
    | '/community/requests'
    | '/community'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/compare'
    | '/pricing'
    | '/profile'
    | '/stays'
    | '/tracker'
    | '/city/$cityId'
    | '/community/$peerId'
    | '/community/requests'
    | '/community/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  CompareRoute: typeof CompareRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  StaysRoute: typeof StaysRoute
  TrackerRoute: typeof TrackerRoute
  CityCityIdRoute: typeof CityCityIdRoute
  CommunityPeerIdRoute: typeof CommunityPeerIdRoute
  CommunityRequestsRoute: typeof CommunityRequestsRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$cityId': {
      id: '/city/$cityId'
      path: '/city/$cityId'
      fullPath: '/city/$cityId'
      preLoaderRoute: typeof CityCityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$peerId': {
      id: '/community/$peerId'
      path: '/community/$peerId'
      fullPath: '/community/$peerId'
      preLoaderRoute: typeof CommunityPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/requests': {
      id: '/community/requests'
      path: '/community/requests'
      fullPath: '/community/requests'
      preLoaderRoute: typeof CommunityRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  CompareRoute: CompareRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  StaysRoute: StaysRoute,
  TrackerRoute: TrackerRoute,
  CityCityIdRoute: CityCityIdRoute,
  CommunityPeerIdRoute: CommunityPeerIdRoute,
  CommunityRequestsRoute: CommunityRequestsRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
