/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as CreatorTermsRouteImport } from './routes/creator-terms'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HowWeMakeMoneyRouteImport } from './routes/how-we-make-money'
import { Route as KitRouteImport } from './routes/kit'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OrgRouteImport } from './routes/org'
import { Route as PensionRouteImport } from './routes/pension'
import { Route as PhrasebookRouteImport } from './routes/phrasebook'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordRouteImport } from './routes/record'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as LangSplatRouteImport } from './routes/$lang.$'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminCreatorsRouteImport } from './routes/admin.creators'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as BusinessExplainRouteImport } from './routes/business.explain'
import { Route as CityCityIdRouteImport } from './routes/city.$cityId'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityPeerIdRouteImport } from './routes/community.$peerId'
import { Route as CommunityRequestsRouteImport } from './routes/community.requests'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalImprintRouteImport } from './routes/legal.imprint'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as PlanIndexRouteImport } from './routes/plan.index'
import { Route as PlanChecklistRouteImport } from './routes/plan.checklist'
import { Route as PlanCostsRouteImport } from './routes/plan.costs'
import { Route as PlanTaxExitRouteImport } from './routes/plan.tax-exit'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'
import { Route as RecordIndexRouteImport } from './routes/record.index'
import { Route as RecordVaultRouteImport } from './routes/record.vault'
import { Route as RulesSlugRouteImport } from './routes/rules.$slug'
import { Route as SettingsEmployerSharingRouteImport } from './routes/settings.employer-sharing'
import { Route as SetupCompanyRouteImport } from './routes/setup.company'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as RecordReportYearRouteImport } from './routes/record.report.$year'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorTermsRoute = CreatorTermsRouteImport.update({
  id: '/creator-terms',
  path: '/creator-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeMakeMoneyRoute = HowWeMakeMoneyRouteImport.update({
  id: '/how-we-make-money',
  path: '/how-we-make-money',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const PensionRoute = PensionRouteImport.update({
  id: '/pension',
  path: '/pension',
  getParentRoute: () => rootRouteImport,
} as any)
const PhrasebookRoute = PhrasebookRouteImport.update({
  id: '/phrasebook',
  path: '/phrasebook',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSplatRoute = LangSplatRouteImport.update({
  id: '/$lang/$',
  path: '/$lang/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCreatorsRoute = AdminCreatorsRouteImport.update({
  id: '/admin/creators',
  path: '/admin/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessExplainRoute = BusinessExplainRouteImport.update({
  id: '/business/explain',
  path: '/business/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCityIdRoute = CityCityIdRouteImport.update({
  id: '/city/$cityId',
  path: '/city/$cityId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPeerIdRoute = CommunityPeerIdRouteImport.update({
  id: '/community/$peerId',
  path: '/community/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRequestsRoute = CommunityRequestsRouteImport.update({
  id: '/community/requests',
  path: '/community/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalImprintRoute = LegalImprintRouteImport.update({
  id: '/legal/imprint',
  path: '/legal/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanRoute,
} as any)
const PlanChecklistRoute = PlanChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => PlanRoute,
} as any)
const PlanCostsRoute = PlanCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => PlanRoute,
} as any)
const PlanTaxExitRoute = PlanTaxExitRouteImport.update({
  id: '/tax-exit',
  path: '/tax-exit',
  getParentRoute: () => PlanRoute,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => PlansRoute,
} as any)
const RecordIndexRoute = RecordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordRoute,
} as any)
const RecordVaultRoute = RecordVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => RecordRoute,
} as any)
const RulesSlugRoute = RulesSlugRouteImport.update({
  id: '/rules/$slug',
  path: '/rules/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEmployerSharingRoute = SettingsEmployerSharingRouteImport.update({
  id: '/settings/employer-sharing',
  path: '/settings/employer-sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupCompanyRoute = SetupCompanyRouteImport.update({
  id: '/setup/company',
  path: '/setup/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecordReportYearRoute = RecordReportYearRouteImport.update({
  id: '/report/$year',
  path: '/report/$year',
  getParentRoute: () => RecordRoute,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/creator': typeof CreatorRoute
  '/creator-terms': typeof CreatorTermsRoute
  '/creators': typeof CreatorsRoute
  '/emergency': typeof EmergencyRoute
  '/explore': typeof ExploreRoute
  '/how-we-make-money': typeof HowWeMakeMoneyRoute
  '/kit': typeof KitRoute
  '/landing': typeof LandingRoute
  '/mcp': typeof McpRoute
  '/org': typeof OrgRoute
  '/pension': typeof PensionRoute
  '/phrasebook': typeof PhrasebookRoute
  '/plan': typeof PlanRouteWithChildren
  '/plans': typeof PlansRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stays': typeof StaysRoute
  '/tracker': typeof TrackerRoute
  '/$lang/$': typeof LangSplatRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/creators': typeof AdminCreatorsRoute
  '/business/explain': typeof BusinessExplainRoute
  '/city/$cityId': typeof CityCityIdRoute
  '/community/$peerId': typeof CommunityPeerIdRoute
  '/community/requests': typeof CommunityRequestsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/plan/checklist': typeof PlanChecklistRoute
  '/plan/costs': typeof PlanCostsRoute
  '/plan/tax-exit': typeof PlanTaxExitRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/record/vault': typeof RecordVaultRoute
  '/rules/$slug': typeof RulesSlugRoute
  '/settings/employer-sharing': typeof SettingsEmployerSharingRoute
  '/setup/company': typeof SetupCompanyRoute
  '/business/': typeof BusinessIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/record/': typeof RecordIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/record/report/$year': typeof RecordReportYearRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/creator': typeof CreatorRoute
  '/creator-terms': typeof CreatorTermsRoute
  '/creators': typeof CreatorsRoute
  '/emergency': typeof EmergencyRoute
  '/explore': typeof ExploreRoute
  '/how-we-make-money': typeof HowWeMakeMoneyRoute
  '/kit': typeof KitRoute
  '/landing': typeof LandingRoute
  '/mcp': typeof McpRoute
  '/org': typeof OrgRoute
  '/pension': typeof PensionRoute
  '/phrasebook': typeof PhrasebookRoute
  '/plans': typeof PlansRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stays': typeof StaysRoute
  '/tracker': typeof TrackerRoute
  '/$lang/$': typeof LangSplatRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/creators': typeof AdminCreatorsRoute
  '/business/explain': typeof BusinessExplainRoute
  '/city/$cityId': typeof CityCityIdRoute
  '/community/$peerId': typeof CommunityPeerIdRoute
  '/community/requests': typeof CommunityRequestsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/plan/checklist': typeof PlanChecklistRoute
  '/plan/costs': typeof PlanCostsRoute
  '/plan/tax-exit': typeof PlanTaxExitRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/record/vault': typeof RecordVaultRoute
  '/rules/$slug': typeof RulesSlugRoute
  '/settings/employer-sharing': typeof SettingsEmployerSharingRoute
  '/setup/company': typeof SetupCompanyRoute
  '/business': typeof BusinessIndexRoute
  '/community': typeof CommunityIndexRoute
  '/plan': typeof PlanIndexRoute
  '/record': typeof RecordIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/record/report/$year': typeof RecordReportYearRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/compare': typeof CompareRoute
  '/creator': typeof CreatorRoute
  '/creator-terms': typeof CreatorTermsRoute
  '/creators': typeof CreatorsRoute
  '/emergency': typeof EmergencyRoute
  '/explore': typeof ExploreRoute
  '/how-we-make-money': typeof HowWeMakeMoneyRoute
  '/kit': typeof KitRoute
  '/landing': typeof LandingRoute
  '/mcp': typeof McpRoute
  '/org': typeof OrgRoute
  '/pension': typeof PensionRoute
  '/phrasebook': typeof PhrasebookRoute
  '/plan': typeof PlanRouteWithChildren
  '/plans': typeof PlansRouteWithChildren
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stays': typeof StaysRoute
  '/tracker': typeof TrackerRoute
  '/$lang/$': typeof LangSplatRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/creators': typeof AdminCreatorsRoute
  '/business/explain': typeof BusinessExplainRoute
  '/city/$cityId': typeof CityCityIdRoute
  '/community/$peerId': typeof CommunityPeerIdRoute
  '/community/requests': typeof CommunityRequestsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/plan/checklist': typeof PlanChecklistRoute
  '/plan/costs': typeof PlanCostsRoute
  '/plan/tax-exit': typeof PlanTaxExitRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/record/vault': typeof RecordVaultRoute
  '/rules/$slug': typeof RulesSlugRoute
  '/settings/employer-sharing': typeof SettingsEmployerSharingRoute
  '/setup/company': typeof SetupCompanyRoute
  '/business/': typeof BusinessIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/record/': typeof RecordIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/record/report/$year': typeof RecordReportYearRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculator'
    | '/compare'
    | '/creator'
    | '/creator-terms'
    | '/creators'
    | '/emergency'
    | '/explore'
    | '/how-we-make-money'
    | '/kit'
    | '/landing'
    | '/mcp'
    | '/org'
    | '/pension'
    | '/phrasebook'
    | '/plan'
    | '/plans'
    | '/pricing'
    | '/profile'
    | '/record'
    | '/sitemap.xml'
    | '/stays'
    | '/tracker'
    | '/$lang/$'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/creators'
    | '/business/explain'
    | '/city/$cityId'
    | '/community/$peerId'
    | '/community/requests'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/plan/checklist'
    | '/plan/costs'
    | '/plan/tax-exit'
    | '/plans/$planId'
    | '/record/vault'
    | '/rules/$slug'
    | '/settings/employer-sharing'
    | '/setup/company'
    | '/business/'
    | '/community/'
    | '/plan/'
    | '/record/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/record/report/$year'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculator'
    | '/compare'
    | '/creator'
    | '/creator-terms'
    | '/creators'
    | '/emergency'
    | '/explore'
    | '/how-we-make-money'
    | '/kit'
    | '/landing'
    | '/mcp'
    | '/org'
    | '/pension'
    | '/phrasebook'
    | '/plans'
    | '/pricing'
    | '/profile'
    | '/sitemap.xml'
    | '/stays'
    | '/tracker'
    | '/$lang/$'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/creators'
    | '/business/explain'
    | '/city/$cityId'
    | '/community/$peerId'
    | '/community/requests'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/plan/checklist'
    | '/plan/costs'
    | '/plan/tax-exit'
    | '/plans/$planId'
    | '/record/vault'
    | '/rules/$slug'
    | '/settings/employer-sharing'
    | '/setup/company'
    | '/business'
    | '/community'
    | '/plan'
    | '/record'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/record/report/$year'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calculator'
    | '/compare'
    | '/creator'
    | '/creator-terms'
    | '/creators'
    | '/emergency'
    | '/explore'
    | '/how-we-make-money'
    | '/kit'
    | '/landing'
    | '/mcp'
    | '/org'
    | '/pension'
    | '/phrasebook'
    | '/plan'
    | '/plans'
    | '/pricing'
    | '/profile'
    | '/record'
    | '/sitemap.xml'
    | '/stays'
    | '/tracker'
    | '/$lang/$'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/creators'
    | '/business/explain'
    | '/city/$cityId'
    | '/community/$peerId'
    | '/community/requests'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/plan/checklist'
    | '/plan/costs'
    | '/plan/tax-exit'
    | '/plans/$planId'
    | '/record/vault'
    | '/rules/$slug'
    | '/settings/employer-sharing'
    | '/setup/company'
    | '/business/'
    | '/community/'
    | '/plan/'
    | '/record/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/record/report/$year'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  CompareRoute: typeof CompareRoute
  CreatorRoute: typeof CreatorRoute
  CreatorTermsRoute: typeof CreatorTermsRoute
  CreatorsRoute: typeof CreatorsRoute
  EmergencyRoute: typeof EmergencyRoute
  ExploreRoute: typeof ExploreRoute
  HowWeMakeMoneyRoute: typeof HowWeMakeMoneyRoute
  KitRoute: typeof KitRoute
  LandingRoute: typeof LandingRoute
  McpRoute: typeof McpRoute
  OrgRoute: typeof OrgRoute
  PensionRoute: typeof PensionRoute
  PhrasebookRoute: typeof PhrasebookRoute
  PlanRoute: typeof PlanRouteWithChildren
  PlansRoute: typeof PlansRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RecordRoute: typeof RecordRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaysRoute: typeof StaysRoute
  TrackerRoute: typeof TrackerRoute
  LangSplatRoute: typeof LangSplatRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminCreatorsRoute: typeof AdminCreatorsRoute
  BusinessExplainRoute: typeof BusinessExplainRoute
  CityCityIdRoute: typeof CityCityIdRoute
  CommunityPeerIdRoute: typeof CommunityPeerIdRoute
  CommunityRequestsRoute: typeof CommunityRequestsRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImprintRoute: typeof LegalImprintRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  RulesSlugRoute: typeof RulesSlugRoute
  SettingsEmployerSharingRoute: typeof SettingsEmployerSharingRoute
  SetupCompanyRoute: typeof SetupCompanyRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-terms': {
      id: '/creator-terms'
      path: '/creator-terms'
      fullPath: '/creator-terms'
      preLoaderRoute: typeof CreatorTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-make-money': {
      id: '/how-we-make-money'
      path: '/how-we-make-money'
      fullPath: '/how-we-make-money'
      preLoaderRoute: typeof HowWeMakeMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pension': {
      id: '/pension'
      path: '/pension'
      fullPath: '/pension'
      preLoaderRoute: typeof PensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrasebook': {
      id: '/phrasebook'
      path: '/phrasebook'
      fullPath: '/phrasebook'
      preLoaderRoute: typeof PhrasebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/$': {
      id: '/$lang/$'
      path: '/$lang/$'
      fullPath: '/$lang/$'
      preLoaderRoute: typeof LangSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/creators': {
      id: '/admin/creators'
      path: '/admin/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AdminCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/explain': {
      id: '/business/explain'
      path: '/business/explain'
      fullPath: '/business/explain'
      preLoaderRoute: typeof BusinessExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$cityId': {
      id: '/city/$cityId'
      path: '/city/$cityId'
      fullPath: '/city/$cityId'
      preLoaderRoute: typeof CityCityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$peerId': {
      id: '/community/$peerId'
      path: '/community/$peerId'
      fullPath: '/community/$peerId'
      preLoaderRoute: typeof CommunityPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/requests': {
      id: '/community/requests'
      path: '/community/requests'
      fullPath: '/community/requests'
      preLoaderRoute: typeof CommunityRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/imprint': {
      id: '/legal/imprint'
      path: '/legal/imprint'
      fullPath: '/legal/imprint'
      preLoaderRoute: typeof LegalImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/': {
      id: '/plan/'
      path: '/'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/checklist': {
      id: '/plan/checklist'
      path: '/checklist'
      fullPath: '/plan/checklist'
      preLoaderRoute: typeof PlanChecklistRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/costs': {
      id: '/plan/costs'
      path: '/costs'
      fullPath: '/plan/costs'
      preLoaderRoute: typeof PlanCostsRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/tax-exit': {
      id: '/plan/tax-exit'
      path: '/tax-exit'
      fullPath: '/plan/tax-exit'
      preLoaderRoute: typeof PlanTaxExitRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof PlansRoute
    }
    '/record/': {
      id: '/record/'
      path: '/'
      fullPath: '/record/'
      preLoaderRoute: typeof RecordIndexRouteImport
      parentRoute: typeof RecordRoute
    }
    '/record/vault': {
      id: '/record/vault'
      path: '/vault'
      fullPath: '/record/vault'
      preLoaderRoute: typeof RecordVaultRouteImport
      parentRoute: typeof RecordRoute
    }
    '/rules/$slug': {
      id: '/rules/$slug'
      path: '/rules/$slug'
      fullPath: '/rules/$slug'
      preLoaderRoute: typeof RulesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/employer-sharing': {
      id: '/settings/employer-sharing'
      path: '/settings/employer-sharing'
      fullPath: '/settings/employer-sharing'
      preLoaderRoute: typeof SettingsEmployerSharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/company': {
      id: '/setup/company'
      path: '/setup/company'
      fullPath: '/setup/company'
      preLoaderRoute: typeof SetupCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/report/$year': {
      id: '/record/report/$year'
      path: '/report/$year'
      fullPath: '/record/report/$year'
      preLoaderRoute: typeof RecordReportYearRouteImport
      parentRoute: typeof RecordRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlanRouteChildren {
  PlanChecklistRoute: typeof PlanChecklistRoute
  PlanCostsRoute: typeof PlanCostsRoute
  PlanTaxExitRoute: typeof PlanTaxExitRoute
  PlanIndexRoute: typeof PlanIndexRoute
}

const PlanRouteChildren: PlanRouteChildren = {
  PlanChecklistRoute: PlanChecklistRoute,
  PlanCostsRoute: PlanCostsRoute,
  PlanTaxExitRoute: PlanTaxExitRoute,
  PlanIndexRoute: PlanIndexRoute,
}

const PlanRouteWithChildren = PlanRoute._addFileChildren(PlanRouteChildren)

interface PlansRouteChildren {
  PlansPlanIdRoute: typeof PlansPlanIdRoute
}

const PlansRouteChildren: PlansRouteChildren = {
  PlansPlanIdRoute: PlansPlanIdRoute,
}

const PlansRouteWithChildren = PlansRoute._addFileChildren(PlansRouteChildren)

interface RecordRouteChildren {
  RecordVaultRoute: typeof RecordVaultRoute
  RecordIndexRoute: typeof RecordIndexRoute
  RecordReportYearRoute: typeof RecordReportYearRoute
}

const RecordRouteChildren: RecordRouteChildren = {
  RecordVaultRoute: RecordVaultRoute,
  RecordIndexRoute: RecordIndexRoute,
  RecordReportYearRoute: RecordReportYearRoute,
}

const RecordRouteWithChildren =
  RecordRoute._addFileChildren(RecordRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  CompareRoute: CompareRoute,
  CreatorRoute: CreatorRoute,
  CreatorTermsRoute: CreatorTermsRoute,
  CreatorsRoute: CreatorsRoute,
  EmergencyRoute: EmergencyRoute,
  ExploreRoute: ExploreRoute,
  HowWeMakeMoneyRoute: HowWeMakeMoneyRoute,
  KitRoute: KitRoute,
  LandingRoute: LandingRoute,
  McpRoute: McpRoute,
  OrgRoute: OrgRoute,
  PensionRoute: PensionRoute,
  PhrasebookRoute: PhrasebookRoute,
  PlanRoute: PlanRouteWithChildren,
  PlansRoute: PlansRouteWithChildren,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RecordRoute: RecordRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaysRoute: StaysRoute,
  TrackerRoute: TrackerRoute,
  LangSplatRoute: LangSplatRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminCreatorsRoute: AdminCreatorsRoute,
  BusinessExplainRoute: BusinessExplainRoute,
  CityCityIdRoute: CityCityIdRoute,
  CommunityPeerIdRoute: CommunityPeerIdRoute,
  CommunityRequestsRoute: CommunityRequestsRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImprintRoute: LegalImprintRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  RulesSlugRoute: RulesSlugRoute,
  SettingsEmployerSharingRoute: SettingsEmployerSharingRoute,
  SetupCompanyRoute: SetupCompanyRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
