-- Driftly: cities table + full 25-city verified seed dataset.

CREATE TABLE IF NOT EXISTS public.cities (
  id text PRIMARY KEY,
  city text NOT NULL,
  country text NOT NULL,
  country_code text NOT NULL,
  region text NOT NULL,
  lat double precision NOT NULL,
  lng double precision NOT NULL,
  local_currency text NOT NULL,
  costs jsonb NOT NULL,
  scores jsonb NOT NULL,
  visa jsonb NOT NULL,
  tax jsonb NOT NULL,
  arbitrage_note text NOT NULL,
  nearest_airport_iata text,
  overland_neighbours text[] NOT NULL DEFAULT '{}',
  last_verified date NOT NULL,
  confidence text NOT NULL CHECK (confidence IN ('low','medium','high')),
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.cities TO anon;
GRANT SELECT ON public.cities TO authenticated;
GRANT ALL ON public.cities TO service_role;

ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Cities are publicly readable" ON public.cities;
CREATE POLICY "Cities are publicly readable"
  ON public.cities FOR SELECT
  TO anon, authenticated
  USING (true);

INSERT INTO public.cities
  (id, city, country, country_code, region, lat, lng, local_currency,
   costs, scores, visa, tax, arbitrage_note, last_verified, confidence)
VALUES
  ('lisbon-pt', 'Lisbon', 'Portugal', 'PT', 'Europe', 38.7223, -9.1393, 'EUR', '{"rent1brCentral": 1450, "rent1brOutskirts": 1000, "colivingRoom": 900, "coworkingHotDesk": 190, "groceriesMonthly": 320, "mealInexpensive": 14, "utilities": 115, "mobileData": 20, "transportMonthly": 45, "gymMonthly": 45, "totalMonthlyMidRange": 2350, "totalMonthlyLean": 1600}'::jsonb, '{"internetSpeedMbps": 180, "safety": 4.5, "nomadCommunity": 5.0, "walkability": 4.5, "englishFriendly": 4.5, "weather": 4.5}'::jsonb, '{"ruleType": "SCHENGEN_90_180", "touristDays": 90, "windowDays": 180, "nomadVisa": {"name": "D8 Digital Nomad Visa", "exists": true, "minMonthlyIncomeUSD": 3600, "durationMonths": 12, "renewable": true, "pathToResidency": true, "notes": "Requires ~4x Portuguese minimum wage in monthly income, proof of remote contract or freelance clients, NIF number, and Portuguese bank account."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "The old NHR regime closed to new entrants; a narrower successor (IFICI) targets scientific and high-value activity. Assume standard progressive rates unless you qualify.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Prices rose sharply 2022-2026. Still strong for the infrastructure, but no longer the bargain it was.', '2026-08-04', 'medium'),
  ('chiang-mai-th', 'Chiang Mai', 'Thailand', 'TH', 'Asia', 18.7883, 98.9853, 'THB', '{"rent1brCentral": 420, "rent1brOutskirts": 280, "colivingRoom": 400, "coworkingHotDesk": 110, "groceriesMonthly": 220, "mealInexpensive": 3, "utilities": 70, "mobileData": 12, "transportMonthly": 60, "gymMonthly": 30, "totalMonthlyMidRange": 1050, "totalMonthlyLean": 700}'::jsonb, '{"internetSpeedMbps": 220, "safety": 4.5, "nomadCommunity": 5.0, "walkability": 3.0, "englishFriendly": 3.5, "weather": 3.5}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 60, "extensionDays": 30, "windowDays": null, "nomadVisa": {"name": "Destination Thailand Visa (DTV)", "exists": true, "requiredSavingsUSD": 13500, "durationMonths": 60, "staysPerEntryDays": 180, "renewable": true, "pathToResidency": false, "notes": "5-year multi-entry. Each entry allows 180 days, extendable once by 180 more (up to 360 consecutive days). Requires 500,000 THB held for at least 3 months — recent large deposits and crypto transfers are red flags. Must be applied for from outside Thailand."}}'::jsonb, '{"residencyTriggerDays": 180, "taxYear": "calendar", "notes": "180+ days in a calendar year makes you Thai tax resident. Since 2024 Thailand taxes foreign income remitted into Thailand by residents. Remittance timing matters.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Best cost-to-infrastructure ratio on this list. Burning season (Feb-Apr) is a real air-quality problem; plan around it.', '2026-08-04', 'medium'),
  ('bangkok-th', 'Bangkok', 'Thailand', 'TH', 'Asia', 13.7563, 100.5018, 'THB', '{"rent1brCentral": 750, "rent1brOutskirts": 420, "colivingRoom": 600, "coworkingHotDesk": 150, "groceriesMonthly": 280, "mealInexpensive": 4, "utilities": 90, "mobileData": 12, "transportMonthly": 70, "gymMonthly": 55, "totalMonthlyMidRange": 1550, "totalMonthlyLean": 1000}'::jsonb, '{"internetSpeedMbps": 250, "safety": 4.0, "nomadCommunity": 4.5, "walkability": 3.0, "englishFriendly": 3.5, "weather": 3.0}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 60, "extensionDays": 30, "windowDays": null, "nomadVisa": {"name": "Destination Thailand Visa (DTV)", "exists": true, "requiredSavingsUSD": 13500, "durationMonths": 60, "staysPerEntryDays": 180, "renewable": true, "pathToResidency": false}}'::jsonb, '{"residencyTriggerDays": 180, "taxYear": "calendar", "notes": "Same remittance-basis rules as Chiang Mai.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'World-class transit, hospitals and airport connectivity for under half of Western European cost.', '2026-08-04', 'medium'),
  ('mexico-city-mx', 'Mexico City', 'Mexico', 'MX', 'Latin America', 19.4326, -99.1332, 'MXN', '{"rent1brCentral": 1100, "rent1brOutskirts": 650, "colivingRoom": 750, "coworkingHotDesk": 160, "groceriesMonthly": 300, "mealInexpensive": 8, "utilities": 55, "mobileData": 18, "transportMonthly": 30, "gymMonthly": 50, "totalMonthlyMidRange": 1850, "totalMonthlyLean": 1200}'::jsonb, '{"internetSpeedMbps": 150, "safety": 3.5, "nomadCommunity": 5.0, "walkability": 4.0, "englishFriendly": 3.0, "weather": 4.5}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 180, "windowDays": null, "nomadVisa": {"name": "Temporary Resident Visa (economic solvency)", "exists": true, "minMonthlyIncomeUSD": 4400, "alternativeSavingsUSD": 73000, "durationMonths": 12, "renewable": true, "renewableUpToYears": 4, "pathToResidency": true, "notes": "Not branded a nomad visa but functions as one. Must be applied for at a Mexican consulate abroad, not inside Mexico. Thresholds are pegged to Mexican minimum wage and move annually."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Day count is one test; having your ''centre of vital interests'' in Mexico can trigger residency independently.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Border officers increasingly grant less than 180 days at their discretion. Do not assume the full stamp.', '2026-08-04', 'medium'),
  ('medellin-co', 'Medellín', 'Colombia', 'CO', 'Latin America', 6.2442, -75.5812, 'COP', '{"rent1brCentral": 700, "rent1brOutskirts": 420, "colivingRoom": 550, "coworkingHotDesk": 130, "groceriesMonthly": 240, "mealInexpensive": 6, "utilities": 60, "mobileData": 15, "transportMonthly": 35, "gymMonthly": 40, "totalMonthlyMidRange": 1350, "totalMonthlyLean": 900}'::jsonb, '{"internetSpeedMbps": 160, "safety": 3.5, "nomadCommunity": 4.5, "walkability": 3.5, "englishFriendly": 2.5, "weather": 5.0}'::jsonb, '{"ruleType": "ROLLING_PER_YEAR", "touristDays": 90, "extensionDays": 90, "maxDaysPerCalendarYear": 180, "nomadVisa": {"name": "V-Visa Digital Nomad", "exists": true, "minMonthlyIncomeUSD": 900, "durationMonths": 24, "renewable": false, "pathToResidency": false, "notes": "Among the lowest income thresholds worldwide (roughly 3x Colombian minimum wage). Does not count toward permanent residency."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "windowNote": "183 days across any rolling 365-day period, which can straddle two tax years.", "notes": "Colombian tax residents are taxed on worldwide income. This catches long-stay nomads more often than they expect.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Year-round spring climate, strong founder scene in El Poblado and Laureles. Petty crime and drink-spiking are genuine risks; the app should surface safety guidance, not hide it.', '2026-08-04', 'medium'),
  ('buenos-aires-ar', 'Buenos Aires', 'Argentina', 'AR', 'Latin America', -34.6037, -58.3816, 'ARS', '{"rent1brCentral": 700, "rent1brOutskirts": 450, "colivingRoom": 550, "coworkingHotDesk": 140, "groceriesMonthly": 280, "mealInexpensive": 9, "utilities": 70, "mobileData": 15, "transportMonthly": 25, "gymMonthly": 45, "totalMonthlyMidRange": 1450, "totalMonthlyLean": 950}'::jsonb, '{"internetSpeedMbps": 130, "safety": 3.5, "nomadCommunity": 4.0, "walkability": 4.5, "englishFriendly": 3.0, "weather": 4.0}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 90, "extensionDays": 90, "nomadVisa": {"name": "Digital Nomad Visa", "exists": true, "minMonthlyIncomeUSD": 1500, "durationMonths": 6, "renewable": true, "pathToResidency": false}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Currency and capital-control regime has been volatile; verify the current FX situation before committing to a long lease.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Costs swing hard with the peso. Highly volatile — treat these figures as low-confidence and refresh often.', '2026-08-04', 'low'),
  ('bali-id', 'Canggu / Bali', 'Indonesia', 'ID', 'Asia', -8.6478, 115.1385, 'IDR', '{"rent1brCentral": 750, "rent1brOutskirts": 450, "colivingRoom": 650, "coworkingHotDesk": 170, "groceriesMonthly": 260, "mealInexpensive": 4, "utilities": 90, "mobileData": 10, "transportMonthly": 80, "gymMonthly": 60, "totalMonthlyMidRange": 1550, "totalMonthlyLean": 1000}'::jsonb, '{"internetSpeedMbps": 90, "safety": 4.0, "nomadCommunity": 5.0, "walkability": 2.0, "englishFriendly": 4.0, "weather": 4.0}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 30, "extensionDays": 30, "nomadVisa": {"name": "E33G Remote Worker KITAS", "exists": true, "minAnnualIncomeUSD": 60000, "durationMonths": 12, "renewable": true, "pathToResidency": false, "notes": "Requires proof of employment or contracts with a company outside Indonesia. Income from Indonesian sources is not permitted."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "E33G holders are generally not taxed on foreign-sourced income, but crossing 183 days on other visa types can trigger residency.", "foreignIncomeExemptForNomadVisa": true}'::jsonb, 'Internet is the weak point — always verify actual speeds at the specific villa, not the island average. Scooter accidents are the top health risk; insurance often excludes them without a local licence.', '2026-08-04', 'medium'),
  ('tbilisi-ge', 'Tbilisi', 'Georgia', 'GE', 'Europe', 41.7151, 44.8271, 'GEL', '{"rent1brCentral": 600, "rent1brOutskirts": 380, "colivingRoom": 500, "coworkingHotDesk": 120, "groceriesMonthly": 230, "mealInexpensive": 7, "utilities": 75, "mobileData": 10, "transportMonthly": 15, "gymMonthly": 40, "totalMonthlyMidRange": 1250, "totalMonthlyLean": 850}'::jsonb, '{"internetSpeedMbps": 140, "safety": 4.5, "nomadCommunity": 4.0, "walkability": 4.0, "englishFriendly": 3.5, "weather": 3.5}'::jsonb, '{"ruleType": "ROLLING_PER_YEAR", "touristDays": 365, "windowDays": 365, "nomadVisa": {"name": "Remotely from Georgia", "exists": true, "minMonthlyIncomeUSD": 2000, "durationMonths": 12, "renewable": true, "pathToResidency": false, "notes": "Largely redundant given the 365-day visa-free stay for 90+ nationalities."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Small Business Status offers 1% tax on turnover up to 500,000 GEL/yr (~USD 180k) for registered individual entrepreneurs. Turnover above the cap is taxed at 3%. This is the single biggest tax arbitrage on this list for freelancers.", "foreignIncomeExemptForNomadVisa": false, "specialRegime": {"name": "Small Business Status", "rate": "1% of turnover, 3% above cap", "turnoverCapGEL": 500000, "turnoverCapUSD": 180000}}'::jsonb, '365 days visa-free plus a 1% freelancer tax regime is the strongest combined visa+tax play available. Banking has become harder for some nationalities — verify before relying on it.', '2026-08-04', 'medium'),
  ('budapest-hu', 'Budapest', 'Hungary', 'HU', 'Europe', 47.4979, 19.0402, 'HUF', '{"rent1brCentral": 800, "rent1brOutskirts": 550, "colivingRoom": 650, "coworkingHotDesk": 160, "groceriesMonthly": 290, "mealInexpensive": 11, "utilities": 140, "mobileData": 18, "transportMonthly": 30, "gymMonthly": 45, "totalMonthlyMidRange": 1650, "totalMonthlyLean": 1150}'::jsonb, '{"internetSpeedMbps": 200, "safety": 4.5, "nomadCommunity": 4.0, "walkability": 4.5, "englishFriendly": 3.5, "weather": 3.5}'::jsonb, '{"ruleType": "SCHENGEN_90_180", "touristDays": 90, "windowDays": 180, "nomadVisa": {"name": "White Card", "exists": true, "minMonthlyIncomeUSD": 3500, "durationMonths": 12, "renewable": true, "pathToResidency": false}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Flat 15% personal income tax. White Card holders are generally not permitted to work for Hungarian companies.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Cheapest EU capital with genuinely good infrastructure. Schengen clock applies.', '2026-08-04', 'medium'),
  ('belgrade-rs', 'Belgrade', 'Serbia', 'RS', 'Europe', 44.7866, 20.4489, 'RSD', '{"rent1brCentral": 650, "rent1brOutskirts": 430, "colivingRoom": 520, "coworkingHotDesk": 130, "groceriesMonthly": 250, "mealInexpensive": 8, "utilities": 110, "mobileData": 15, "transportMonthly": 25, "gymMonthly": 40, "totalMonthlyMidRange": 1350, "totalMonthlyLean": 900}'::jsonb, '{"internetSpeedMbps": 170, "safety": 4.0, "nomadCommunity": 3.5, "walkability": 4.0, "englishFriendly": 3.5, "weather": 3.5}'::jsonb, '{"ruleType": "ROLLING_PER_YEAR", "touristDays": 90, "windowDays": 180, "nomadVisa": {"name": "Digital Nomad residence permit", "exists": true, "minMonthlyIncomeUSD": 1500, "durationMonths": 12, "renewable": true, "pathToResidency": true, "notes": "Non-Schengen, so time here does not burn Schengen days."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Serbia offers a foreign-income exemption for qualifying nomads in the first 90 days. Non-Schengen status makes it a useful ''reset'' base between EU stints.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Prime Schengen-clock parking spot. Cheap, in the European timezone, and days spent here do not count against your 90/180.', '2026-08-04', 'medium'),
  ('istanbul-tr', 'Istanbul', 'Türkiye', 'TR', 'Europe', 41.0082, 28.9784, 'TRY', '{"rent1brCentral": 750, "rent1brOutskirts": 450, "colivingRoom": 600, "coworkingHotDesk": 140, "groceriesMonthly": 270, "mealInexpensive": 7, "utilities": 90, "mobileData": 20, "transportMonthly": 35, "gymMonthly": 45, "totalMonthlyMidRange": 1500, "totalMonthlyLean": 1000}'::jsonb, '{"internetSpeedMbps": 120, "safety": 3.5, "nomadCommunity": 3.5, "walkability": 4.0, "englishFriendly": 3.0, "weather": 4.0}'::jsonb, '{"ruleType": "ROLLING_PER_YEAR", "touristDays": 90, "windowDays": 180, "nomadVisa": {"name": "Digital Nomad Visa", "exists": true, "minMonthlyIncomeUSD": 3000, "durationMonths": 12, "renewable": true, "pathToResidency": false, "notes": "Age 21-55, university degree required."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "High inflation environment; local-currency figures go stale fast.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Non-Schengen with a major airline hub. Inflation makes cost data unusually volatile — refresh monthly.', '2026-08-04', 'low'),
  ('warsaw-pl', 'Warsaw', 'Poland', 'PL', 'Europe', 52.2297, 21.0122, 'PLN', '{"rent1brCentral": 950, "rent1brOutskirts": 680, "colivingRoom": 700, "coworkingHotDesk": 180, "groceriesMonthly": 320, "mealInexpensive": 12, "utilities": 160, "mobileData": 12, "transportMonthly": 35, "gymMonthly": 45, "totalMonthlyMidRange": 1900, "totalMonthlyLean": 1300}'::jsonb, '{"internetSpeedMbps": 230, "safety": 4.5, "nomadCommunity": 3.5, "walkability": 4.0, "englishFriendly": 4.0, "weather": 3.0}'::jsonb, '{"ruleType": "SCHENGEN_90_180", "touristDays": 90, "windowDays": 180, "nomadVisa": {"name": "None dedicated", "exists": false, "notes": "No dedicated nomad visa. Freelancers typically use the national D-visa or B2B self-employment route."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Registered sole traders can access a lump-sum 12-15% IT services rate, which is attractive for developers.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Best internet and safety per dollar in the EU. Strong startup and developer talent pool for founder collaboration.', '2026-08-04', 'medium'),
  ('prague-cz', 'Prague', 'Czechia', 'CZ', 'Europe', 50.0755, 14.4378, 'CZK', '{"rent1brCentral": 1150, "rent1brOutskirts": 820, "colivingRoom": 800, "coworkingHotDesk": 200, "groceriesMonthly": 340, "mealInexpensive": 12, "utilities": 190, "mobileData": 22, "transportMonthly": 25, "gymMonthly": 50, "totalMonthlyMidRange": 2100, "totalMonthlyLean": 1450}'::jsonb, '{"internetSpeedMbps": 210, "safety": 4.5, "nomadCommunity": 4.0, "walkability": 5.0, "englishFriendly": 4.0, "weather": 3.0}'::jsonb, '{"ruleType": "SCHENGEN_90_180", "touristDays": 90, "windowDays": 180, "nomadVisa": {"name": "Digital Nomad Visa (Highly Qualified Employees programme)", "exists": true, "minMonthlyIncomeUSD": 3300, "durationMonths": 12, "renewable": true, "pathToResidency": false, "notes": "Limited to nationals of a specific eligible list, IT/tech focused."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "The ''živnostenský list'' trade licence with the 60/40 flat expense deduction is a long-standing freelancer play.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Very walkable, excellent transit, mature freelancer legal framework.', '2026-08-04', 'medium'),
  ('las-palmas-es', 'Las Palmas de Gran Canaria', 'Spain', 'ES', 'Europe', 28.1235, -15.4363, 'EUR', '{"rent1brCentral": 1050, "rent1brOutskirts": 750, "colivingRoom": 800, "coworkingHotDesk": 170, "groceriesMonthly": 300, "mealInexpensive": 13, "utilities": 95, "mobileData": 20, "transportMonthly": 35, "gymMonthly": 40, "totalMonthlyMidRange": 1950, "totalMonthlyLean": 1350}'::jsonb, '{"internetSpeedMbps": 190, "safety": 4.5, "nomadCommunity": 4.5, "walkability": 4.5, "englishFriendly": 3.5, "weather": 5.0}'::jsonb, '{"ruleType": "SCHENGEN_90_180", "touristDays": 90, "windowDays": 180, "nomadVisa": {"name": "Visado de Teletrabajo Internacional", "exists": true, "minMonthlyIncomeUSD": 3100, "durationMonths": 12, "renewable": true, "renewableUpToYears": 5, "pathToResidency": true, "notes": "Roughly 200% of Spanish SMI. Freelancers may earn no more than 20% of income from Spanish clients."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Nomad visa holders may apply for the Beckham Law regime: flat 24% on Spanish-source income up to EUR 600k for up to 6 years. Canary Islands also have reduced IGIC (7%) instead of mainland VAT (21%).", "foreignIncomeExemptForNomadVisa": false, "specialRegime": {"name": "Beckham Law", "rate": "24% flat up to EUR 600k", "years": 6}}'::jsonb, 'Best year-round climate in the EU, and the Beckham Law makes Spain unusually attractive for high earners despite headline rates.', '2026-08-04', 'medium'),
  ('athens-gr', 'Athens', 'Greece', 'GR', 'Europe', 37.9838, 23.7275, 'EUR', '{"rent1brCentral": 900, "rent1brOutskirts": 620, "colivingRoom": 700, "coworkingHotDesk": 165, "groceriesMonthly": 300, "mealInexpensive": 13, "utilities": 145, "mobileData": 25, "transportMonthly": 32, "gymMonthly": 45, "totalMonthlyMidRange": 1800, "totalMonthlyLean": 1250}'::jsonb, '{"internetSpeedMbps": 130, "safety": 4.0, "nomadCommunity": 4.0, "walkability": 4.0, "englishFriendly": 4.0, "weather": 4.5}'::jsonb, '{"ruleType": "SCHENGEN_90_180", "touristDays": 90, "windowDays": 180, "nomadVisa": {"name": "Digital Nomad Visa", "exists": true, "minMonthlyIncomeUSD": 4000, "durationMonths": 12, "renewable": true, "pathToResidency": true}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "50% income tax exemption for 7 years for qualifying new tax residents who commit to staying 2+ years.", "foreignIncomeExemptForNomadVisa": false, "specialRegime": {"name": "New tax resident 50% exemption", "rate": "50% of income exempt", "years": 7}}'::jsonb, 'Cheapest Eurozone capital with a real nomad scene. Summer heat is increasingly severe.', '2026-08-04', 'medium'),
  ('tallinn-ee', 'Tallinn', 'Estonia', 'EE', 'Europe', 59.437, 24.7536, 'EUR', '{"rent1brCentral": 950, "rent1brOutskirts": 680, "colivingRoom": 720, "coworkingHotDesk": 190, "groceriesMonthly": 330, "mealInexpensive": 15, "utilities": 180, "mobileData": 18, "transportMonthly": 0, "gymMonthly": 50, "totalMonthlyMidRange": 1950, "totalMonthlyLean": 1400}'::jsonb, '{"internetSpeedMbps": 240, "safety": 4.5, "nomadCommunity": 3.5, "walkability": 4.5, "englishFriendly": 4.5, "weather": 2.0}'::jsonb, '{"ruleType": "SCHENGEN_90_180", "touristDays": 90, "windowDays": 180, "nomadVisa": {"name": "Digital Nomad Visa (Type D)", "exists": true, "minMonthlyIncomeUSD": 4900, "durationMonths": 12, "renewable": false, "pathToResidency": false, "notes": "The world''s first dedicated nomad visa (2020). Income threshold is gross, and high."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "e-Residency lets you run an EU company remotely, but it grants no residency, no visa, and does not change your personal tax residence. Widely misunderstood.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Best digital government on earth. Public transport is free for residents. Winter darkness is a real quality-of-life factor.', '2026-08-04', 'medium'),
  ('dubai-ae', 'Dubai', 'United Arab Emirates', 'AE', 'Middle East', 25.2048, 55.2708, 'AED', '{"rent1brCentral": 2200, "rent1brOutskirts": 1400, "colivingRoom": 1300, "coworkingHotDesk": 300, "groceriesMonthly": 450, "mealInexpensive": 14, "utilities": 180, "mobileData": 60, "transportMonthly": 90, "gymMonthly": 80, "totalMonthlyMidRange": 3600, "totalMonthlyLean": 2400}'::jsonb, '{"internetSpeedMbps": 280, "safety": 5.0, "nomadCommunity": 4.0, "walkability": 2.0, "englishFriendly": 5.0, "weather": 2.5}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 30, "extensionDays": 30, "nomadVisa": {"name": "Virtual Working Programme", "exists": true, "minMonthlyIncomeUSD": 3500, "durationMonths": 12, "renewable": true, "pathToResidency": false}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "0% personal income tax. 9% corporate tax applies above AED 375k profit.", "foreignIncomeExemptForNomadVisa": true, "personalIncomeTaxRate": 0}'::jsonb, 'Expensive to live, but 0% income tax flips the arbitrage math entirely above roughly USD 120k/yr. The calculator must model post-tax income, not just cost of living.', '2026-08-04', 'medium'),
  ('kuala-lumpur-my', 'Kuala Lumpur', 'Malaysia', 'MY', 'Asia', 3.139, 101.6869, 'MYR', '{"rent1brCentral": 620, "rent1brOutskirts": 380, "colivingRoom": 500, "coworkingHotDesk": 130, "groceriesMonthly": 250, "mealInexpensive": 4, "utilities": 65, "mobileData": 12, "transportMonthly": 35, "gymMonthly": 45, "totalMonthlyMidRange": 1300, "totalMonthlyLean": 850}'::jsonb, '{"internetSpeedMbps": 200, "safety": 4.0, "nomadCommunity": 3.5, "walkability": 3.0, "englishFriendly": 4.5, "weather": 3.0}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 90, "nomadVisa": {"name": "DE Rantau Nomad Pass", "exists": true, "minAnnualIncomeUSD": 24000, "durationMonths": 12, "renewable": true, "renewableUpToYears": 2, "pathToResidency": false, "notes": "Restricted to IT, digital marketing, content and similar digital professions."}}'::jsonb, '{"residencyTriggerDays": 182, "taxYear": "calendar", "notes": "Foreign-sourced income remitted to Malaysia is exempt for individuals through at least 2026 — verify the current sunset date.", "foreignIncomeExemptForNomadVisa": true}'::jsonb, 'Most underrated on this list: English-speaking, great internet, cheap, good healthcare, major airport hub. Weak nomad social scene compared to Bali or Chiang Mai.', '2026-08-04', 'medium'),
  ('ho-chi-minh-vn', 'Ho Chi Minh City', 'Vietnam', 'VN', 'Asia', 10.8231, 106.6297, 'VND', '{"rent1brCentral": 550, "rent1brOutskirts": 350, "colivingRoom": 450, "coworkingHotDesk": 120, "groceriesMonthly": 210, "mealInexpensive": 3, "utilities": 75, "mobileData": 8, "transportMonthly": 40, "gymMonthly": 40, "totalMonthlyMidRange": 1150, "totalMonthlyLean": 750}'::jsonb, '{"internetSpeedMbps": 160, "safety": 4.0, "nomadCommunity": 4.0, "walkability": 2.5, "englishFriendly": 3.0, "weather": 3.0}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 90, "nomadVisa": {"name": "None dedicated", "exists": false, "notes": "No nomad visa. The 90-day e-visa (single or multiple entry) is the practical route."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Residents taxed on worldwide income at progressive rates up to 35%. Enforcement against foreigners has historically been light but is tightening.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, '90-day e-visa is generous and easy. Air quality and traffic noise are the main complaints.', '2026-08-04', 'medium'),
  ('taipei-tw', 'Taipei', 'Taiwan', 'TW', 'Asia', 25.033, 121.5654, 'TWD', '{"rent1brCentral": 950, "rent1brOutskirts": 620, "colivingRoom": 700, "coworkingHotDesk": 180, "groceriesMonthly": 330, "mealInexpensive": 6, "utilities": 70, "mobileData": 20, "transportMonthly": 40, "gymMonthly": 55, "totalMonthlyMidRange": 1800, "totalMonthlyLean": 1200}'::jsonb, '{"internetSpeedMbps": 260, "safety": 5.0, "nomadCommunity": 3.5, "walkability": 4.5, "englishFriendly": 3.0, "weather": 3.0}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 90, "nomadVisa": {"name": "Employment Gold Card", "exists": true, "minMonthlyIncomeUSD": 5500, "durationMonths": 36, "renewable": true, "pathToResidency": true, "notes": "Combines work permit, residence visa, ARC and re-entry permit in one."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Gold Card holders get a 50% exemption on income over TWD 3m for the first 5 years of residency.", "foreignIncomeExemptForNomadVisa": false, "specialRegime": {"name": "Gold Card 50% exemption", "rate": "50% exempt above TWD 3m", "years": 5}}'::jsonb, 'Safest city on this list, world-class transit and internet. The Gold Card is one of the best-value long-term nomad permits anywhere.', '2026-08-04', 'medium'),
  ('seoul-kr', 'Seoul', 'South Korea', 'KR', 'Asia', 37.5665, 126.978, 'KRW', '{"rent1brCentral": 1150, "rent1brOutskirts": 780, "colivingRoom": 850, "coworkingHotDesk": 220, "groceriesMonthly": 450, "mealInexpensive": 8, "utilities": 130, "mobileData": 35, "transportMonthly": 50, "gymMonthly": 70, "totalMonthlyMidRange": 2350, "totalMonthlyLean": 1600}'::jsonb, '{"internetSpeedMbps": 300, "safety": 5.0, "nomadCommunity": 3.0, "walkability": 4.5, "englishFriendly": 2.5, "weather": 3.0}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 90, "nomadVisa": {"name": "Workation Visa (F-1-D)", "exists": true, "minAnnualIncomeUSD": 65000, "durationMonths": 12, "renewable": true, "renewableUpToYears": 2, "pathToResidency": false, "notes": "Requires income of at least twice Korea''s GNI per capita and 1+ year with the same employer."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Progressive rates up to 45%. High income threshold on the visa means most holders are exposed.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Fastest internet on the list. High income bar and weak English make it a specialist choice.', '2026-08-04', 'medium'),
  ('cape-town-za', 'Cape Town', 'South Africa', 'ZA', 'Africa', -33.9249, 18.4241, 'ZAR', '{"rent1brCentral": 800, "rent1brOutskirts": 500, "colivingRoom": 650, "coworkingHotDesk": 150, "groceriesMonthly": 280, "mealInexpensive": 9, "utilities": 110, "mobileData": 25, "transportMonthly": 90, "gymMonthly": 45, "totalMonthlyMidRange": 1650, "totalMonthlyLean": 1100}'::jsonb, '{"internetSpeedMbps": 130, "safety": 2.5, "nomadCommunity": 4.0, "walkability": 2.5, "englishFriendly": 5.0, "weather": 4.5}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 90, "nomadVisa": {"name": "Remote Work Visa", "exists": true, "minAnnualIncomeUSD": 34000, "durationMonths": 36, "renewable": true, "pathToResidency": false, "notes": "Holders staying under 6 months in a 12-month window are exempt from SA income tax registration."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "March-February", "notes": "NON-CALENDAR TAX YEAR: 1 March to 28/29 February. Also uses a separate ''ordinarily resident'' test. Day-count alone is not the whole picture.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Extraordinary scenery and value in the European timezone, but violent crime rates are genuinely high and load-shedding can disrupt work. Do not soften this in the UI.', '2026-08-04', 'medium'),
  ('mauritius-mu', 'Port Louis / Grand Baie', 'Mauritius', 'MU', 'Africa', -20.1609, 57.5012, 'MUR', '{"rent1brCentral": 750, "rent1brOutskirts": 500, "colivingRoom": 650, "coworkingHotDesk": 150, "groceriesMonthly": 320, "mealInexpensive": 7, "utilities": 85, "mobileData": 20, "transportMonthly": 60, "gymMonthly": 45, "totalMonthlyMidRange": 1700, "totalMonthlyLean": 1150}'::jsonb, '{"internetSpeedMbps": 100, "safety": 4.5, "nomadCommunity": 3.0, "walkability": 2.0, "englishFriendly": 4.5, "weather": 4.5}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 90, "nomadVisa": {"name": "Premium Travel Visa", "exists": true, "minMonthlyIncomeUSD": 1500, "durationMonths": 12, "renewable": true, "pathToResidency": false, "notes": "Free to apply. One of the easiest approvals on this list."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "July-June", "notes": "NON-CALENDAR TAX YEAR: 1 July to 30 June. Flat 15% income tax; foreign income not remitted to Mauritius is generally not taxed.", "foreignIncomeExemptForNomadVisa": true}'::jsonb, 'Free visa, 15% flat tax, English-speaking, safe. Isolated and car-dependent; flights are expensive.', '2026-08-04', 'medium'),
  ('tirana-al', 'Tirana', 'Albania', 'AL', 'Europe', 41.3275, 19.8187, 'ALL', '{"rent1brCentral": 550, "rent1brOutskirts": 350, "colivingRoom": 450, "coworkingHotDesk": 110, "groceriesMonthly": 240, "mealInexpensive": 7, "utilities": 85, "mobileData": 15, "transportMonthly": 20, "gymMonthly": 35, "totalMonthlyMidRange": 1200, "totalMonthlyLean": 800}'::jsonb, '{"internetSpeedMbps": 110, "safety": 4.0, "nomadCommunity": 3.0, "walkability": 4.0, "englishFriendly": 3.5, "weather": 4.0}'::jsonb, '{"ruleType": "ROLLING_PER_YEAR", "touristDays": 365, "windowDays": 365, "nomadVisa": {"name": "Unique Permit for Digital Nomads", "exists": true, "minMonthlyIncomeUSD": 850, "durationMonths": 12, "renewable": true, "renewableUpToYears": 5, "pathToResidency": true, "notes": "Very low income threshold. 1-year visa-free stay for US citizens makes the permit optional for many."}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Nomad permit holders have been granted a foreign-income exemption in the first year. Verify current status before relying on it.", "foreignIncomeExemptForNomadVisa": true}'::jsonb, 'Non-Schengen, dirt cheap, 365-day visa-free for US passports, on the Adriatic. The dark horse of European arbitrage.', '2026-08-04', 'medium'),
  ('playa-del-carmen-mx', 'Playa del Carmen', 'Mexico', 'MX', 'Latin America', 20.6296, -87.0739, 'MXN', '{"rent1brCentral": 950, "rent1brOutskirts": 600, "colivingRoom": 750, "coworkingHotDesk": 170, "groceriesMonthly": 330, "mealInexpensive": 9, "utilities": 100, "mobileData": 18, "transportMonthly": 30, "gymMonthly": 55, "totalMonthlyMidRange": 1800, "totalMonthlyLean": 1200}'::jsonb, '{"internetSpeedMbps": 120, "safety": 3.5, "nomadCommunity": 4.5, "walkability": 4.0, "englishFriendly": 4.5, "weather": 4.0}'::jsonb, '{"ruleType": "FIXED_PER_ENTRY", "touristDays": 180, "nomadVisa": {"name": "Temporary Resident Visa (economic solvency)", "exists": true, "minMonthlyIncomeUSD": 4400, "durationMonths": 12, "renewable": true, "renewableUpToYears": 4, "pathToResidency": true}}'::jsonb, '{"residencyTriggerDays": 183, "taxYear": "calendar", "notes": "Same as Mexico City.", "foreignIncomeExemptForNomadVisa": false}'::jsonb, 'Caribbean beach plus a real nomad scene, US timezone overlap. Sargassum season (Apr-Aug) and humidity are the trade-offs.', '2026-08-04', 'medium')
ON CONFLICT (id) DO UPDATE SET
  city = EXCLUDED.city,
  country = EXCLUDED.country,
  country_code = EXCLUDED.country_code,
  region = EXCLUDED.region,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  local_currency = EXCLUDED.local_currency,
  costs = EXCLUDED.costs,
  scores = EXCLUDED.scores,
  visa = EXCLUDED.visa,
  tax = EXCLUDED.tax,
  arbitrage_note = EXCLUDED.arbitrage_note,
  last_verified = EXCLUDED.last_verified,
  confidence = EXCLUDED.confidence;
