name: Deploy Ollama and Open WebUI

on:
  workflow_dispatch:

jobs:
  Ollama-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: bitovi/github-actions-deploy-ollama@v0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          ollama_models: "phi3"
          disable_signup: "true"
